# Site settings
title:  Alexander's Blog
SEOTitle:  Alexander's Blog
header-img: "https://dlseeu-website.oss-cn-hangzhou.aliyuncs.com/bg/home-bg.png"
email: dlseeu@gmail.com
description: "关于编程技能，硬件知识，思考方式，发现并记录一个更加有趣的世界"
keyword: "嵌入式，多媒体，安防，互联网，郑浩"
url: "http://dlseeu.cn"              # your host, for absolute URL
baseurl: ""         # for example, '/blog' if your blog hosted on 'host/blog'


# SNS settings
RSS: false
zhihu_username:     bryant81
github_username:    dlseeu


# Build settings
# from 2016, 'pygments' is unsupported on GitHub Pages. Use 'rouge' for highlighting instead.
highlighter: rouge
permalink: pretty
paginate: 10
exclude: ["less","node_modules","Gruntfile.js","package.json","README.md"]
anchorjs: true                          # if you want to customize anchor. check out line:181 of `post.html`


# Gems
# from PR#40, to support local preview for Jekyll 3.0
plugins:
    - jekyll-paginate


# Markdown settings
# replace redcarpet to kramdown,
# although redcarpet can auto highlight code, the lack of header-id make the catalog impossible, so I switch to kramdown
# document: http://jekyllrb.com/docs/configuration/#kramdown

encoding: "utf-8"
markdown_ext: "markdown,mkdown,mkdn,mkd,md"
markdown: kramdown
kramdown:
  input: GFM                            # use Github Flavored Markdown !important



# Analytics
analytics:
  provider               : "google"  # false (default), "google", "google-universal", "custom"
  google:
    tracking_id          : "UA-127551216-1"
    anonymize_ip         : # true, false (default)



# Sidebar settings
sidebar: true                           # whether or not using Sidebar.
sidebar-about-description: "发现和记录一个有趣的技术世界"
# use absolute URL, seeing it's used in both `/` and `/about/`
sidebar-avatar: "https://dlseeu-website.oss-cn-hangzhou.aliyuncs.com/head.png" 



# Featured Tags
featured-tags: true                     # whether or not using Feature-Tags
featured-condition-size: 1              # A tag will be featured if the size of it is more than this condition value


# Friends
#friends: [
#    {
#        title: "Hux Blog",
#        href: "http://huangxuan.me"
#    },{
#        title: "Foo",
#        href: "#"
#    },{
#        title: "Bar",
#        href: "#"
#    },{
#        title: "Example Friends",
#        href: "#"
#    },{
#        title: "It helps SEO",
#        href: "#"
#    }
#]
